const pick = (id) => document.querySelector(`#${id}`);

/**
 * 사람별 요약 칸 하나. 칸은 둘로 고정이지만 누가 들어가는지는 로그인 후 정해진다.
 * `me`/`partner`는 자리 이름일 뿐 사람을 뜻하지 않는다.
 */
const memberSlot = (slot) => ({
  row: pick(`${slot}-row`),
  avatar: pick(`${slot}-avatar`),
  name: pick(`${slot}-name`),
  count: pick(`${slot}-count`),
  total: pick(`${slot}-total`),
  ratio: pick(`${slot}-ratio`),
  bar: pick(`${slot}-bar`),
});

/** DOM 참조 한곳 모음. 다른 모듈은 이 객체로만 문서에 접근한다. */
export const elements = {
  memberSlots: [memberSlot("me"), memberSlot("partner")],
  dataGate: document.querySelector("#data-gate"),
  dataStatus: document.querySelector("#data-status"),
  retryLoad: document.querySelector("#retry-load"),
  appShell: document.querySelector("#app-shell"),
  authGate: document.querySelector("#auth-gate"),
  loginForm: document.querySelector("#login-form"),
  loginEmail: document.querySelector("#login-email"),
  loginPassword: document.querySelector("#login-password"),
  loginError: document.querySelector("#login-error"),
  loginSubmit: document.querySelector("#login-submit"),
  loginSubmitLabel: document.querySelector("#login-submit-label"),
  signOut: document.querySelector("#sign-out"),
  openProfile: document.querySelector("#open-profile"),
  openSettings: document.querySelector("#open-settings"),
  pages: [document.querySelector("#profile-page"), document.querySelector("#settings-page")],
  profilePage: document.querySelector("#profile-page"),
  profileForm: document.querySelector("#profile-form"),
  profileName: document.querySelector("#profile-name"),
  profilePalette: document.querySelector("#profile-palette"),
  profilePreview: document.querySelector("#profile-preview"),
  profilePreviewName: document.querySelector("#profile-preview-name"),
  profileError: document.querySelector("#profile-error"),
  profileSubmit: document.querySelector("#profile-submit"),
  settingsPage: document.querySelector("#settings-page"),
  resetForm: document.querySelector("#reset-form"),
  resetWarning: document.querySelector("#reset-warning"),
  resetConfirm: document.querySelector("#reset-confirm"),
  resetError: document.querySelector("#reset-error"),
  resetSubmit: document.querySelector("#reset-submit"),
  total: document.querySelector("#monthly-total"),
  monthTitle: document.querySelector("#month-title"),
  monthTrigger: document.querySelector("#month-picker-trigger"),
  prevMonth: document.querySelector("#prev-month"),
  nextMonth: document.querySelector("#next-month"),
  monthSheet: document.querySelector("#month-sheet"),
  closeMonthSheet: document.querySelector("#close-month-sheet"),
  yearLabel: document.querySelector("#year-label"),
  prevYear: document.querySelector("#prev-year"),
  nextYear: document.querySelector("#next-year"),
  monthGrid: document.querySelector("#month-grid"),
  ledgerFilter: document.querySelector("#ledger-filter"),
  count: document.querySelector("#record-count"),
  list: document.querySelector("#expense-list"),
  emptyTemplate: document.querySelector("#empty-template"),
  backdrop: document.querySelector("#sheet-backdrop"),
  sheet: document.querySelector("#entry-sheet"),
  form: document.querySelector("#expense-form"),
  formEyebrow: document.querySelector("#form-eyebrow"),
  formTitle: document.querySelector("#form-title"),
  submit: document.querySelector("#expense-submit"),
  submitLabel: document.querySelector("#submit-label"),
  closeForm: document.querySelector("#close-form"),
  date: document.querySelector("#expense-date"),
  dateDisplay: document.querySelector("#date-display"),
  category: document.querySelector("#expense-category"),
  item: document.querySelector("#expense-item"),
  amount: document.querySelector("#expense-amount"),
  itemError: document.querySelector("#item-error"),
  amountError: document.querySelector("#amount-error"),
  dateError: document.querySelector("#date-error"),
  dateNotice: document.querySelector("#date-notice"),
  notesSheet: document.querySelector("#notes-sheet"),
  notesEyebrow: document.querySelector("#notes-eyebrow"),
  notesTitle: document.querySelector("#notes-title"),
  closeNotes: document.querySelector("#close-notes"),
  noteList: document.querySelector("#note-list"),
  noteForm: document.querySelector("#note-form"),
  noteInput: document.querySelector("#note-input"),
  noteSend: document.querySelector("#note-send"),
  openFixedSheet: document.querySelector("#open-fixed-sheet"),
  fixedSheet: document.querySelector("#fixed-sheet"),
  closeFixedSheet: document.querySelector("#close-fixed-sheet"),
  fixedListView: document.querySelector("#fixed-list-view"),
  fixedList: document.querySelector("#fixed-list"),
  addFixed: document.querySelector("#add-fixed"),
  cancelFixed: document.querySelector("#cancel-fixed"),
  fixedForm: document.querySelector("#fixed-form"),
  fixedDay: document.querySelector("#fixed-day"),
  fixedCategory: document.querySelector("#fixed-category"),
  fixedItem: document.querySelector("#fixed-item"),
  fixedAmount: document.querySelector("#fixed-amount"),
  fixedDayError: document.querySelector("#fixed-day-error"),
  fixedItemError: document.querySelector("#fixed-item-error"),
  fixedAmountError: document.querySelector("#fixed-amount-error"),
  fixedFormMode: document.querySelector("#fixed-form-mode"),
  fixedSubmit: document.querySelector("#fixed-submit"),
  fixedSubmitLabel: document.querySelector("#fixed-submit-label"),
  fixedHint: document.querySelector("#fixed-hint"),
  toast: document.querySelector("#toast"),
  toastMessage: document.querySelector("#toast-message"),
  undoDelete: document.querySelector("#undo-delete"),
};
